language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update --dev --no-interaction

phpunit: phpunit --dev

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - php vendor/bin/coveralls -v
